game_details:
  :Directions: "This is standard game you love!\nEnter the first letter of an item to select it."
  :Options: 
      1 Player:
        :num_players: 2
        :description: Play against the computer
        :player_types:
        - human
        - computer
      2 Player:
        :num_players: 2
        :description: Play against a friend
        :player_types:
        - human
        - human
      Simulation:
        :num_players: 2
        :description: Watch the computer play
        :player_types:
        - computer
        - computer

win_states:
- Tie
- Player 1
- Player 0

item_list: 
- rock
- paper
- scissors

score_that_wins: 3
initial_score: 0
thinking_time: 1.5
pause_time: 0.3