game_details:
  :Directions: "Enter the first letter of an item to select it.\nGo to this site to learn which itmes win http://www.samkass.com/theories/RPSSL.html"
  :Options: 
      1 Player:
        :num_players: 2
        :description: Play against the computer
        :player_types:
        - human
        - computer
      2 Player:
        :num_players: 2
        :description: Play against a friend
        :player_types:
        - human
        - human
      Simulation:
        :num_players: 2
        :description: Watch the computer play
        :player_types:
        - computer
        - computer

win_states:
- Tie
- Player 0
- Player 1
- Player 0
- Player 1


